// <auto-generated />
using System;
using GestionCommerciale.Shared.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionCommerciale.Shared.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707215044_AddProductionQualitySettings")]
    partial class AddProductionQualitySettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GestionCommerciale.Modules.AvoirFournisseur.Models.AvoirFournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RetourMarchandise")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AvoirsFournisseurs");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.AvoirFournisseur.Models.AvoirFournisseurLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvoirFournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Remise")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AvoirFournisseurId");

                    b.ToTable("AvoirFournisseurLignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Charges.Models.CategorieCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CategoriesCharges", (string)null);
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Charges.Models.Charge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieChargeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fournisseur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantTtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategorieChargeId");

                    b.HasIndex("Date");

                    b.HasIndex("FournisseurId");

                    b.ToTable("Charges", (string)null);
                });

            modelBuilder.Entity("GestionCommerciale.Modules.CommandeClient.Models.BonCommandeClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DevisId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FactureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FactureId");

                    b.ToTable("BonsCommandeClient");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.CommandeClient.Models.BonCommandeClientLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonCommandeClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantiteCommandee")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Remise")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BonCommandeClientId");

                    b.ToTable("BonCommandeClientLignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.CommandeFournisseur.Models.BonCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BonsCommande");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.CommandeFournisseur.Models.BonCommandeLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonCommandeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantiteCommandee")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Remise")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BonCommandeId");

                    b.ToTable("BonCommandeLignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Devis.Models.Devis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateValidite")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemiseGlobale")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Devis");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Devis.Models.DevisLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DevisId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Remise")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DevisId");

                    b.ToTable("DevisLignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.Avoir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FactureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RetourMarchandise")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FactureId");

                    b.ToTable("Avoirs");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.AvoirLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvoirId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Remise")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AvoirId");

                    b.ToTable("AvoirLignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.Facture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BonCommandeReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DevisId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstPayee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemiseGlobale")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalTtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.FactureLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BonLivraisonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FactureId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Remise")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BonLivraisonId");

                    b.HasIndex("FactureId");

                    b.ToTable("FactureLignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FactureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Montant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FactureId");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.FactureFournisseur.Models.FactureFournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstPayee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemiseGlobale")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalTtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FacturesFournisseurs");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.FactureFournisseur.Models.FactureFournisseurLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BonReceptionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FactureFournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Remise")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BonReceptionId");

                    b.HasIndex("FactureFournisseurId");

                    b.ToTable("FactureFournisseurLignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.FactureFournisseur.Models.PaiementFournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FactureFournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Montant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FactureFournisseurId");

                    b.ToTable("PaiementsFournisseurs");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Livraison.Models.BonLivraison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BonCommandeClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DevisId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FactureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BonCommandeClientId");

                    b.HasIndex("FactureId");

                    b.ToTable("BonsLivraison");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Livraison.Models.BonLivraisonLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BLId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantiteCommandee")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantiteLivree")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Remise")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BLId");

                    b.ToTable("BonLivraisonLignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Production.Models.CategorieCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordre")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.HasIndex("Ordre");

                    b.ToTable("CategoriesCommande", (string)null);
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Production.Models.CommandeProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieCommandeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateExpiration")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstTerminee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixAchatNaissainHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantiteNaissain")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TauxMortalite")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeHuitreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategorieCommandeId");

                    b.HasIndex("DateCommande");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("TypeHuitreId");

                    b.ToTable("CommandesProduction", (string)null);
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Production.Models.OperationProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommandeProductionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OperationAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PochetteGrand")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PochetteMoyenne")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PochettePetit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tables")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommandeProductionId");

                    b.HasIndex("OperationAt");

                    b.ToTable("OperationsProduction", (string)null);
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Production.Models.TypeHuitre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordre")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.HasIndex("Ordre");

                    b.ToTable("TypesHuitre", (string)null);
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Reception.Models.BonReception", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BonCommandeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommandeProductionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FactureFournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalTtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BonCommandeId");

                    b.HasIndex("CommandeProductionId");

                    b.HasIndex("FactureFournisseurId");

                    b.ToTable("BonsReception");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Reception.Models.BonReceptionLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BRId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantiteRecue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BRId");

                    b.ToTable("BonReceptionLignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Stock.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Stock.Models.MouvementStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrigineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrigineType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockAvant")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.ToTable("MouvementsStock");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Stock.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeBarre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("BLOB");

                    b.Property<decimal>("PrixAchatHT")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixVenteHT")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockActuel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockMinimum")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Tiers.Models.Tiers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionsPaiement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ICE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tiers", (string)null);
                });

            modelBuilder.Entity("GestionCommerciale.Shared.Database.AppSettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgrandissementMaxJours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackupDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("BackupEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackupIntervalHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackupIntervalUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BackupRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BlocageSiStockInsuffisant")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DevisValiditeJoursDefaut")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Devise")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNumberingFloorsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableVirtualKeyboard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportanceTauxAgrandissement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportanceTauxMortalite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastBackupDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocieteAdresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SocieteICE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SocieteLogoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocieteMentionsLegales")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocieteNom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TauxTVAJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TrialStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UiLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.AvoirFournisseur.Models.AvoirFournisseurLigne", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.AvoirFournisseur.Models.AvoirFournisseur", "AvoirFournisseur")
                        .WithMany("Lignes")
                        .HasForeignKey("AvoirFournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvoirFournisseur");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Charges.Models.Charge", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Charges.Models.CategorieCharge", "CategorieCharge")
                        .WithMany()
                        .HasForeignKey("CategorieChargeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionCommerciale.Modules.Tiers.Models.Tiers", null)
                        .WithMany()
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CategorieCharge");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.CommandeClient.Models.BonCommandeClient", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Facturation.Models.Facture", "Facture")
                        .WithMany()
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.CommandeClient.Models.BonCommandeClientLigne", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.CommandeClient.Models.BonCommandeClient", "BonCommandeClient")
                        .WithMany("Lignes")
                        .HasForeignKey("BonCommandeClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonCommandeClient");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.CommandeFournisseur.Models.BonCommandeLigne", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.CommandeFournisseur.Models.BonCommande", "BonCommande")
                        .WithMany("Lignes")
                        .HasForeignKey("BonCommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonCommande");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Devis.Models.DevisLigne", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Devis.Models.Devis", "Devis")
                        .WithMany("Lignes")
                        .HasForeignKey("DevisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Devis");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.Avoir", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Facturation.Models.Facture", "Facture")
                        .WithMany()
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.AvoirLigne", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Facturation.Models.Avoir", "Avoir")
                        .WithMany("Lignes")
                        .HasForeignKey("AvoirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avoir");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.FactureLigne", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Livraison.Models.BonLivraison", "BonLivraison")
                        .WithMany()
                        .HasForeignKey("BonLivraisonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestionCommerciale.Modules.Facturation.Models.Facture", "Facture")
                        .WithMany("Lignes")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonLivraison");

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.Paiement", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Facturation.Models.Facture", "Facture")
                        .WithMany("Paiements")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.FactureFournisseur.Models.FactureFournisseurLigne", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Reception.Models.BonReception", "BonReception")
                        .WithMany()
                        .HasForeignKey("BonReceptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestionCommerciale.Modules.FactureFournisseur.Models.FactureFournisseur", "FactureFournisseur")
                        .WithMany("Lignes")
                        .HasForeignKey("FactureFournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonReception");

                    b.Navigation("FactureFournisseur");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.FactureFournisseur.Models.PaiementFournisseur", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.FactureFournisseur.Models.FactureFournisseur", "FactureFournisseur")
                        .WithMany("Paiements")
                        .HasForeignKey("FactureFournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FactureFournisseur");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Livraison.Models.BonLivraison", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.CommandeClient.Models.BonCommandeClient", null)
                        .WithMany()
                        .HasForeignKey("BonCommandeClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestionCommerciale.Modules.Facturation.Models.Facture", "Facture")
                        .WithMany()
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Livraison.Models.BonLivraisonLigne", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Livraison.Models.BonLivraison", "BonLivraison")
                        .WithMany("Lignes")
                        .HasForeignKey("BLId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonLivraison");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Production.Models.CommandeProduction", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Production.Models.CategorieCommande", "CategorieCommande")
                        .WithMany()
                        .HasForeignKey("CategorieCommandeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionCommerciale.Modules.Tiers.Models.Tiers", "Fournisseur")
                        .WithMany()
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionCommerciale.Modules.Production.Models.TypeHuitre", "TypeHuitre")
                        .WithMany()
                        .HasForeignKey("TypeHuitreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategorieCommande");

                    b.Navigation("Fournisseur");

                    b.Navigation("TypeHuitre");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Production.Models.OperationProduction", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Production.Models.CommandeProduction", "CommandeProduction")
                        .WithMany("Operations")
                        .HasForeignKey("CommandeProductionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CommandeProduction");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Reception.Models.BonReception", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.CommandeFournisseur.Models.BonCommande", "BonCommande")
                        .WithMany()
                        .HasForeignKey("BonCommandeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestionCommerciale.Modules.Production.Models.CommandeProduction", "CommandeProduction")
                        .WithMany()
                        .HasForeignKey("CommandeProductionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestionCommerciale.Modules.FactureFournisseur.Models.FactureFournisseur", null)
                        .WithMany()
                        .HasForeignKey("FactureFournisseurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BonCommande");

                    b.Navigation("CommandeProduction");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Reception.Models.BonReceptionLigne", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Reception.Models.BonReception", "BonReception")
                        .WithMany("Lignes")
                        .HasForeignKey("BRId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonReception");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Stock.Models.MouvementStock", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Stock.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Stock.Models.Produit", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Stock.Models.Categorie", "Categorie")
                        .WithMany()
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.AvoirFournisseur.Models.AvoirFournisseur", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.CommandeClient.Models.BonCommandeClient", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.CommandeFournisseur.Models.BonCommande", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Devis.Models.Devis", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.Avoir", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.Facture", b =>
                {
                    b.Navigation("Lignes");

                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.FactureFournisseur.Models.FactureFournisseur", b =>
                {
                    b.Navigation("Lignes");

                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Livraison.Models.BonLivraison", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Production.Models.CommandeProduction", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Reception.Models.BonReception", b =>
                {
                    b.Navigation("Lignes");
                });
#pragma warning restore 612, 618
        }
    }
}
