// <auto-generated />
using System;
using GestionCommerciale.Shared.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionCommerciale.Shared.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528163543_AddBackupSettings")]
    partial class AddBackupSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GestionCommerciale.Modules.AvoirFournisseur.Models.AvoirFournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RetourMarchandise")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AvoirsFournisseurs");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.AvoirFournisseur.Models.AvoirFournisseurLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvoirFournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Remise")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AvoirFournisseurId");

                    b.ToTable("AvoirFournisseurLignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Commande.Models.BonCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BonsCommande");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Commande.Models.BonCommandeLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonCommandeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantiteCommandee")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BonCommandeId");

                    b.ToTable("BonCommandeLignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Devis.Models.Devis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateValidite")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemiseGlobale")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Devis");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Devis.Models.DevisLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DevisId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Remise")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DevisId");

                    b.ToTable("DevisLignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.Avoir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FactureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RetourMarchandise")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FactureId");

                    b.ToTable("Avoirs");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.AvoirLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvoirId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Remise")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AvoirId");

                    b.ToTable("AvoirLignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.Facture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BLId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DevisId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstPayee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemiseGlobale")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.FactureLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditionnement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FactureId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Remise")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FactureId");

                    b.ToTable("FactureLignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FactureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Montant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FactureId");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Livraison.Models.BonLivraison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DevisId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BonsLivraison");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Livraison.Models.BonLivraisonLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BLId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantiteCommandee")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantiteLivree")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BLId");

                    b.ToTable("BonLivraisonLignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Reception.Models.BonReception", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BonCommandeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BonCommandeId");

                    b.ToTable("BonsReception");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Reception.Models.BonReceptionLigne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BRId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantiteRecue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BRId");

                    b.ToTable("BonReceptionLignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Stock.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Stock.Models.MouvementStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrigineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrigineType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockAvant")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.ToTable("MouvementsStock");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Stock.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeBarre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("BLOB");

                    b.Property<decimal>("PrixAchatHT")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixVenteHT")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockActuel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockMinimum")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Tiers.Models.Tiers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionsPaiement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ICE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tiers", (string)null);
                });

            modelBuilder.Entity("GestionCommerciale.Shared.Database.AppSettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackupDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("BackupEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackupIntervalHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackupRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BlocageSiStockInsuffisant")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DevisValiditeJoursDefaut")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Devise")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableVirtualKeyboard")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastBackupDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocieteAdresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SocieteICE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SocieteLogoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocieteMentionsLegales")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocieteNom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TauxTVAJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TrialStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UiLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.AvoirFournisseur.Models.AvoirFournisseurLigne", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.AvoirFournisseur.Models.AvoirFournisseur", "AvoirFournisseur")
                        .WithMany("Lignes")
                        .HasForeignKey("AvoirFournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvoirFournisseur");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Commande.Models.BonCommandeLigne", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Commande.Models.BonCommande", "BonCommande")
                        .WithMany("Lignes")
                        .HasForeignKey("BonCommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonCommande");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Devis.Models.DevisLigne", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Devis.Models.Devis", "Devis")
                        .WithMany("Lignes")
                        .HasForeignKey("DevisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Devis");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.Avoir", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Facturation.Models.Facture", "Facture")
                        .WithMany()
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.AvoirLigne", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Facturation.Models.Avoir", "Avoir")
                        .WithMany("Lignes")
                        .HasForeignKey("AvoirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avoir");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.FactureLigne", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Facturation.Models.Facture", "Facture")
                        .WithMany("Lignes")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.Paiement", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Facturation.Models.Facture", "Facture")
                        .WithMany("Paiements")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Livraison.Models.BonLivraisonLigne", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Livraison.Models.BonLivraison", "BonLivraison")
                        .WithMany("Lignes")
                        .HasForeignKey("BLId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonLivraison");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Reception.Models.BonReception", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Commande.Models.BonCommande", "BonCommande")
                        .WithMany()
                        .HasForeignKey("BonCommandeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BonCommande");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Reception.Models.BonReceptionLigne", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Reception.Models.BonReception", "BonReception")
                        .WithMany("Lignes")
                        .HasForeignKey("BRId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonReception");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Stock.Models.MouvementStock", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Stock.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Stock.Models.Produit", b =>
                {
                    b.HasOne("GestionCommerciale.Modules.Stock.Models.Categorie", "Categorie")
                        .WithMany()
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.AvoirFournisseur.Models.AvoirFournisseur", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Commande.Models.BonCommande", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Devis.Models.Devis", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.Avoir", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Facturation.Models.Facture", b =>
                {
                    b.Navigation("Lignes");

                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Livraison.Models.BonLivraison", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("GestionCommerciale.Modules.Reception.Models.BonReception", b =>
                {
                    b.Navigation("Lignes");
                });
#pragma warning restore 612, 618
        }
    }
}
